# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


schedules:
- cron: "43 19 * * *"  # This cron expression triggers the pipeline at 7:30 PM every day
  displayName: Daily 6:30 PM build 
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! zainul abid
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $organizationUrl = "https://dev.azure.com/afiqdes/"
      $project = "QC%20and%20Design"
      $queryId = "418f043f-32fd-46c1-80c0-c3cb2cabc432"
      $url = "$organizationUrl$project/_apis/wit/wiql/$queryId?api-version=6.0"
      az boards query --id $queryId --output table

  
