# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

schedules:
- cron: "0 0 * * *"  # Run daily at midnight UTC
  displayName: Daily midnight
  branches:
    include:
    - main

pr: none

jobs:
- job: Send_WorkItem_Query_Email
  displayName: Send Work Item Query Email
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: QueryWorkItems@2
    inputs:
      queryOption: 'directValue'
      queryValue: 'SELECT [System.Id], [System.Title], [System.State], [System.AssignedTo], [System.Tags], [System.WorkItemType] FROM WorkItems WHERE [System.TeamProject] = @project AND [System.WorkItemType] IN GROUP 'Feature', 'User Story', 'Task' AND [System.State] <> 'Closed' AND [System.CreatedDate] > @Today-1'
      project: 'YourProjectName'
      connectedServiceName: 'YourServiceConnectionName'  # The name of your service connection
  - task: SendEmail@1
    inputs:
      to: 'recipient@example.com'
      subject: 'Work Item Query Results'
      body: |
        Here are the work items that match your query:
        
        $(QueryWorkItems.result)
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'))
