# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


schedules:
- cron: "39 11 * * *"  # This cron expression triggers the pipeline at 7:30 PM every day
  displayName: Daily 7:30 PM build 
  branches:
   include:
     - master
     - main

  
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! zainul abid
  displayName: 'Run a one-line script'

- script: |
    echo "Current time is $(date)"  # Print current time
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script abid'
