# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


schedules:
- cron: "10 19 * * *"  # This cron expression triggers the pipeline at 7:30 PM every day
  displayName: Daily 7:00 PM build 
  branches:
   include:
     - master
     - main
  
pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Authenticate with Azure DevOps (using PAT)
      $pat = "y3mfou4yaudgj2bvguedcfqezg4dz6sgrqt4xrkhclsrgsjceusq"
      $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$pat"))
      $organization = "afiqdes"
      $project = "QC%20and%20Design"
      $queryId = "418f043f-32fd-46c1-80c0-c3cb2cabc432"
      $url = "https://dev.azure.com/$organization/$project/_apis/wit/wiql/$queryId"
      $response = Invoke-RestMethod -Uri $url -Method Get -Headers @{Authorization = "Basic $base64AuthInfo"} -Verbose

      foreach ($workItem in $response.workItems) 
      {
          Write-Output $workItem.fields.'System.Title'
      }
  displayName: 'Fetch Work Items'


  
