# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


schedules:
- cron: "39 11 * * *"  # This cron expression triggers the pipeline at 7:30 PM every day
  displayName: Daily 7:30 PM build 
  branches:
   include:
     - master
     - main

  
pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install azure-devops
    pip install azure-devops~=7.1.0  # Ensure you're using a compatible version
  displayName: 'Install Azure DevOps Python SDK'
- script: |
    python -c "from azure.devops.connection import Connection
    from msrest.authentication import BasicAuthentication
    import pprint

    # Fill in with your personal access token and organization URL
    personal_access_token = 'pircqfxw7y6f2mpr2dm6lnkq6bapbwydw2cecwryoxf4ulub3pha'
    organization_url = 'https://dev.azure.com/afiqdes'

    # Create a connection to the Azure DevOps organization
    credentials = BasicAuthentication('', personal_access_token)
    connection = Connection(base_url=organization_url, creds=credentials)

    # Execute your query
    core_client = connection.clients.get_core_client()
    projects = core_client.get_projects()
    pprint.pprint([project.name for project in projects])"
  displayName: 'Execute Azure DevOps Query'
